### ISSUE TITLE
New PCB layout

### ISSUE THREAD

**Issue by uwp-sammckee** [uwp-sammckee/DataLogger#11]

**Comment by PizzaRules668** [comment]
Here is what I am think about for parts

- [Processor](https://www.pjrc.com/store/teensy41.html)
- [LPS25HBTR](https://www.digikey.com/en/products/detail/stmicroelectronics/LPS25HBTR/5043059)
- [BNO055](https://www.digikey.com/en/products/detail/bosch-sensortec/BNO055/6136301)
- Same Flash chip [W25Q128](https://www.digikey.com/en/products/detail/winbond-electronics/W25Q128JVSIQ-TR/

**Comment by PizzaRules668** [comment]
I **think** the latest revision is done
It has 4 Pyro Channels, A Pyro channel Switch, 4 Servo Mounts, 2 buttons (record, dump, [I think I could get rid of them if we want]).

**Comment by uwp-sammckee** [comment]
What's your plan for getting rid of the record and dump buttons?

**Comment by uwp-sammckee** [comment]
Is there a LED for state indication on the new design?

**Comment by uwp-sammckee** [comment]
The board looks good otherwise! I have a couple of questions about what some of the pin outs do, but we can discuss that on Tuesday.

**Comment by PizzaRules668** [comment]
I was thinking we could get rid of the dump button, and we could do the same thing with the erase button where it can only be done by user input.
There is an LED it below the buzzer its an SMD buzzer.

**Comment by PizzaRules668** [comment]
[Digikey Parts List](https://www.digikey.com/en/mylists/list/UNYX1KHIE8)
